export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS'
export const UPDATE_BUILDING_SUCESS = 'UPDATE_BUILDING_SUCCESS'
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS'
